services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_image.entity_manager'
            $imageTypesConfig: '%sfs_image.types%'

    _instanceof:
        Softspring\ImageBundle\Image\NameGeneratorInterface:
            tags: ['sfs_image.name_generator']
        Softspring\ImageBundle\Type\ImageTypeProviderInterface:
            tags: ['sfs_image.image_type_provider']

    Softspring\ImageBundle\Command\:
        resource: '../../src/Command/*'

    Softspring\ImageBundle\Form\:
        resource: '../../src/Form/*'

    Softspring\ImageBundle\Form\ImageTypeSearchFilterForm:
        public: true

    Softspring\ImageBundle\EventListener\:
        resource: '../../src/EventListener/*'

    Softspring\ImageBundle\Image\:
        resource: '../../src/Image/*'

    Softspring\ImageBundle\Manager\:
        resource: '../../src/Manager/*'

    Softspring\ImageBundle\Type\:
        resource: '../../src/Type/*'

    Softspring\ImageBundle\Render\:
        resource: '../../src/Render/*'

    Softspring\ImageBundle\Twig\Extension\:
        resource: '../../src/Twig/Extension/*'
        tags: ['twig.extension']

    Softspring\ImageBundle\EntityListener\ImageVersionListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preRemove', entity: 'Softspring\ImageBundle\Model\ImageVersion' }

    Softspring\ImageBundle\EntityListener\ImageListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preFlush', entity: 'Softspring\ImageBundle\Model\Image',  priority: 10 }
