parameters:
    sfs_image.admin.images.list_view: '@@SfsImage/admin/image/list.html.twig'
    sfs_image.admin.images.list_page_view: '@@SfsImage/admin/image/list-page.html.twig'
    sfs_image.admin.images.create_view: '@@SfsImage/admin/image/create.html.twig'
    sfs_image.admin.images.update_view: '@@SfsImage/admin/image/update.html.twig'
    sfs_image.admin.images.delete_view: '@@SfsImage/admin/image/delete.html.twig'
    sfs_image.admin.images.read_view: '@@SfsImage/admin/image/read.html.twig'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
#        bind:
#            $imageTypes: '%sfs_image.types%'
#            $em: '@sfs_image.entity_manager'

    Softspring\ImageBundle\Form\Admin\:
        resource: '../../../src/Form/Admin/Image*'

    Softspring\ImageBundle\EventListener\Admin\:
        resource: '../../../src/EventListener/Admin/Image*'

    sfs_image.admin.image.controller:
        class: Softspring\Component\CrudlController\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\ImageBundle\Manager\ImageManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\ImageBundle\Form\Admin\ImageListFilterFormInterface'
            $createForm: '@Softspring\ImageBundle\Form\Admin\ImageCreateFormInterface'
            $updateForm: '@Softspring\ImageBundle\Form\Admin\ImageUpdateFormInterface'
            $deleteForm: '@Softspring\ImageBundle\Form\Admin\ImageDeleteFormInterface'
            $config:
                entity_attribute: 'image'
                list:
                    is_granted: 'ROLE_SFS_IMAGE_ADMIN_IMAGES_LIST'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_LIST_VIEW
                    view: '%sfs_image.admin.images.list_view%'
                    view_page: '%sfs_image.admin.images.list_page_view%'
                create:
                    is_granted: 'ROLE_SFS_IMAGE_ADMIN_IMAGES_CREATE'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_CREATE_VIEW
                    success_redirect_to: 'sfs_image_admin_images_list'
                    view: '%sfs_image.admin.images.create_view%'
                update:
                    is_granted: 'ROLE_SFS_IMAGE_ADMIN_IMAGES_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_UPDATE_VIEW
                    success_redirect_to: 'sfs_image_admin_images_list'
                    view: '%sfs_image.admin.images.update_view%'
                delete:
                    is_granted: 'ROLE_SFS_IMAGE_ADMIN_IMAGES_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_DELETE_VIEW
                    success_redirect_to: 'sfs_image_admin_images_list'
                    view: '%sfs_image.admin.images.delete_view%'
                read:
                    is_granted: 'ROLE_SFS_IMAGE_ADMIN_IMAGES_DETAILS'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_READ_INITIALIZE
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_IMAGES_READ_VIEW
                    view: '%sfs_image.admin.images.read_view%'