security:
    role_hierarchy:

        ROLE_SFS_IMAGE_ADMIN_IMAGES_RO:
            - ROLE_SFS_IMAGE_ADMIN_IMAGES_LIST
            - ROLE_SFS_IMAGE_ADMIN_IMAGES_DETAILS
        ROLE_SFS_IMAGE_ADMIN_IMAGES_RW:
            - ROLE_SFS_IMAGE_ADMIN_IMAGES_RO
            - ROLE_SFS_IMAGE_ADMIN_IMAGES_CREATE
            - ROLE_SFS_IMAGE_ADMIN_IMAGES_DELETE
            - ROLE_SFS_IMAGE_ADMIN_IMAGES_UPDATE
