services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
#        bind:
#            $typeTypes: '%sfs_image.type.types%'
#            $em: '@sfs_image.entity_manager'

    Softspring\ImageBundle\Form\Admin\:
        resource: '../../../../Form/Admin/Type*'

#    Softspring\ImageBundle\EventListener\Admin\:
#        resource: '../../../../EventListener/Admin/Type*'

    sfs_image.admin.type.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\ImageBundle\Manager\ImageTypeManagerInterface'
            $listFilterForm: '@Softspring\ImageBundle\Form\Admin\TypeListFilterFormInterface'
            $createForm: '@Softspring\ImageBundle\Form\Admin\TypeCreateFormInterface'
            $updateForm: '@Softspring\ImageBundle\Form\Admin\TypeUpdateFormInterface'
            $deleteForm: '@Softspring\ImageBundle\Form\Admin\TypeDeleteFormInterface'
            $config:
                entity_attribute: 'type'
                list:
                    is_granted: 'ROLE_ADMIN_IMAGE_TYPE_LIST'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_LIST_VIEW
                    view: '@@SfsImage/admin/type/list.html.twig'
                    view_page: '@@SfsImage/admin/type/list-page.html.twig'
                create:
                    is_granted: 'ROLE_ADMIN_IMAGE_TYPE_CREATE'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_CREATE_VIEW
                    success_redirect_to: 'sfs_image_admin_types_list'
                    view: '@@SfsImage/admin/type/create.html.twig'
                update:
                    is_granted: 'ROLE_ADMIN_IMAGE_TYPE_UPDATE'
                    param_converter_key: 'key'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_UPDATE_VIEW
                    success_redirect_to: 'sfs_image_admin_types_list'
                    view: '@@SfsImage/admin/type/update.html.twig'
                delete:
                    is_granted: 'ROLE_ADMIN_IMAGE_TYPE_DELETE'
                    param_converter_key: 'key'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_DELETE_VIEW
                    success_redirect_to: 'sfs_image_admin_types_list'
                    view: '@@SfsImage/admin/type/delete.html.twig'
                read:
                    is_granted: 'ROLE_ADMIN_IMAGE_TYPE_READ'
                    param_converter_key: 'key'
                    initialize_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_READ_INITIALIZE
                    view_event_name: !php/const Softspring\ImageBundle\SfsImageEvents::ADMIN_TYPES_READ_VIEW
                    view: '@@SfsImage/admin/type/read.html.twig'